In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
dataset = pd.read_csv("data/people.csv")
dataset.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer

In [72]:
# Check dataset dimensions
print(f"Number of rows: {dataset.shape[0]}")
print(f"Number of columns: {dataset.shape[1]}")

Number of rows: 1000
Number of columns: 9

In [73]:
dataset.isnull().sum()

Index            0
User Id          0
First Name       0
Last Name        0
Sex              0
Email            0
Phone            0
Date of birth    0
Job Title        0
dtype: int64

In [74]:
dataset.describe()

             Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [75]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          1000 non-null   int64
 1   User Id        1000 non-null   str
 2   First Name     1000 non-null   str
 3   Last Name      1000 non-null   str
 4   Sex            1000 non-null   str
 5   Email          1000 non-null   str
 6   Phone          1000 non-null   str
 7   Date of birth  1000 non-null   str
 8   Job Title      1000 non-null   str
dtypes: int64(1), str(8)
memory usage: 70.4 KB

In [76]:
dataset.dtypes

Index            int64
User Id            str
First Name         str
Last Name          str
Sex                str
Email              str
Phone              str
Date of birth      str
Job Title          str
dtype: object

In [77]:
dataset['Sex'] = dataset['Sex'].astype('category')

In [78]:
dataset.dtypes

Index               int64
User Id               str
First Name            str
Last Name             str
Sex              category
Email                 str
Phone                 str
Date of birth         str
Job Title             str
dtype: object

In [79]:
dataset.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer

In [80]:
dataset['Date of Birth'] = pd.to_datetime(dataset['Date of birth'], format="%Y-%m-%d")

In [81]:
dataset.dtypes

Index                     int64
User Id                     str
First Name                  str
Last Name                   str
Sex                    category
Email                       str
Phone                       str
Date of birth               str
Job Title                   str
Date of Birth    datetime64[us]
dtype: object

In [82]:
dataset.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Date of Birth
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,2014-01-27
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,1931-07-26
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,2013-11-25
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,2012-11-17
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,1923-04-15

In [83]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [84]:
# dataset = pd.get_dummies(dataset, columns=['Sex'])

In [85]:
dataset['Sex'] = encoder.fit_transform(dataset['Sex'])

In [86]:
dataset.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,Date of Birth
0,1,8717bbf45cCDbEe,Shelia,Mahoney,1,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,2014-01-27
1,2,3d5AD30A4cD38ed,Jo,Rivers,0,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,1931-07-26
2,3,810Ce0F276Badec,Sheryl,Lowery,0,fhoward@example.org,(599)782-0605,2013-11-25,Copy,2013-11-25
3,4,BF2a889C00f0cE1,Whitney,Hooper,1,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,2012-11-17
4,5,9afFEafAe1CBBB9,Lindsey,Rice,0,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,1923-04-15

In [87]:
dataset.dtypes

Index                     int64
User Id                     str
First Name                  str
Last Name                   str
Sex                       int64
Email                       str
Phone                       str
Date of birth               str
Job Title                   str
Date of Birth    datetime64[us]
dtype: object