In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

data = {
    "id": range(1, 31),
    "gender": np.random.choice(["Male", "Female"], 30),
    "age": np.random.randint(17, 25, 30),
    "study_hours": np.random.uniform(1, 10, 30),
    "attendance": np.random.uniform(40, 100, 30),
    "marks": np.random.uniform(10, 25, 30),
}

df = pd.DataFrame(data)

In [3]:
df.head()

   id  gender  age  study_hours  attendance      marks
0   1    Male   21     6.467904   63.320637  11.793914
1   2  Female   17     2.534717   56.280942  20.698672
2   3    Male   20     1.585464   89.724251  21.411776
3   4    Male   18     9.539970   61.405200  18.419158
4   5    Male   22     9.690688   56.856071  21.564508

In [4]:
df.dtypes

id               int64
gender             str
age              int64
study_hours    float64
attendance     float64
marks          float64
dtype: object

In [5]:
df['study_hours'] = df['study_hours'].astype(int)

In [6]:
df.dtypes

id               int64
gender             str
age              int64
study_hours      int64
attendance     float64
marks          float64
dtype: object

In [7]:
df.head()

   id  gender  age  study_hours  attendance      marks
0   1    Male   21            6   63.320637  11.793914
1   2  Female   17            2   56.280942  20.698672
2   3    Male   20            1   89.724251  21.411776
3   4    Male   18            9   61.405200  18.419158
4   5    Male   22            9   56.856071  21.564508

In [8]:
df.loc[3, "study_hours"] = np.nan
df.loc[7, "attendance"] = np.nan

df.loc[12, "study_hours"] = 50

In [9]:
df.head()

   id  gender  age  study_hours  attendance      marks
0   1    Male   21          6.0   63.320637  11.793914
1   2  Female   17          2.0   56.280942  20.698672
2   3    Male   20          1.0   89.724251  21.411776
3   4    Male   18          NaN   61.405200  18.419158
4   5    Male   22          9.0   56.856071  21.564508

In [10]:
df.describe()

              id        age  study_hours  attendance      marks
count  30.000000  30.000000    29.000000   29.000000  30.000000
mean   15.500000  20.500000     6.448276   68.267413  17.369192
std     8.803408   2.224472     8.858354   17.738874   4.391635
min     1.000000  17.000000     1.000000   40.331327  10.381287
25%     8.250000  19.000000     2.000000   56.280942  13.508825
50%    15.500000  20.000000     5.000000   63.320637  17.734776
75%    22.750000  22.000000     8.000000   83.776371  21.392149
max    30.000000  24.000000    50.000000   99.213216  23.945465

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           30 non-null     int64
 1   gender       30 non-null     str
 2   age          30 non-null     int64
 3   study_hours  29 non-null     float64
 4   attendance   29 non-null     float64
 5   marks        30 non-null     float64
dtypes: float64(3), int64(2), str(1)
memory usage: 1.5 KB

In [12]:
df.isnull().sum()

id             0
gender         0
age            0
study_hours    1
attendance     1
marks          0
dtype: int64

In [15]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())
df['attendance'] = df['attendance'].fillna(df['attendance'].mean())

In [16]:
df.isnull().sum()

id             0
gender         0
age            0
study_hours    0
attendance     0
marks          0
dtype: int64

In [17]:
df['gender'] = df['gender'].replace({ "M": "Male", "F": "Female", "1": "Male", "0": "Female" })

In [18]:
# Outlier detection

Q1 = df["study_hours"].quantile(0.25)
Q3 = df['study_hours'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['study_hours'] < lower) | (df['study_hours'] > upper)]
outliers

    id gender  age  study_hours  attendance     marks
12  13   Male   18         50.0   40.331327  14.71534

In [19]:
df['study_hours'] = np.where(df['study_hours'] > upper, upper, df['study_hours'])

In [20]:
df['study_hours'] = (df["study_hours"] - df["study_hours"].min()) / (df['study_hours'].max() - df['study_hours'].min())

In [21]:
df['attendance'] = np.log(df['attendance'])

In [23]:
df.head()

   id  gender  age  study_hours  attendance      marks
0   1    Male   21     0.333333    4.148211  11.793914
1   2  Female   17     0.066667    4.030356  20.698672
2   3    Male   20     0.000000    4.496741  21.411776
3   4    Male   18     0.363218    4.117495  18.419158
4   5    Male   22     0.533333    4.040523  21.564508